### ISSUE TITLE
Handle negative counts from `quasi_probability_dist`

### ISSUE THREAD

**Issue by dowusu-antwi** [Infleqtion/client-superstaq#785] opened 2023-09-21 20:52 UTC
### What is happening?

Because we do Measurement Error Mitigation, sometimes there are negative counts. We should convert probability distributions to the nearest possible normalized version. See [here](https://qiskit.org/ecosystem/mthree/probs.html) and [here](https://qiskit.org/documentation/stubs/qiskit.result.QuasiDistribution.html#qiskit.result.QuasiDistribution.nearest_probability_distribution).

### What are the current alternatives?

Round negative counts to zero, i.e., for `cirq.ResultDict` outputs in `cirq_superstaq`.

**Comment by perlinm** [comment] 2023-09-21 21:40
+1 for applying maximum-likelihood corrections rather than setting negative entries to zero.

**Comment by teaguetomesh** [comment] 2023-10-19 16:10
@richrines1 @vtomole - this got brought up during SiW today. Rather than opening a new issue I'll paste my reproducing example here. 

Essentially, I wanted to run the Supermarq bit code benchmarks on IBM Guadalupe, but the `Bitcode.score()` function throws an error because it expects an actual probability distribution to be passed in. Code to reproduce the error:

```python
import cirq_superstaq as css
import supermarq

service = css.Service()
bitcode_job = service.get_job('c27dfa88-8164-4130-af8f-cac83893b27a')
counts1 = bitcode_job.counts()

bitcode_bmark = supermarq.bit_code.BitCode(3, 1, [1,0,1])
bitcode_bmark.score(counts1)
```

**Comment by teaguetomesh** [comment] 2023-10-19 17:12
Two things:
1. Digging into this I realized the benchmark `score` function was failing because I had incorrectly initialized the object with a `str` rather than a `List[int]`. Opened #825 to make sure the benchmarks catch this.
2. The code to properly convert the quasidist back into a regular counts dictionary is given below. (not quite perfect because the final counts are not integers, but we could instead just return a distribution by dividing by total shots)

```python
quasdist = qiskit.result.QuasiDistribution(counts1, shots=bitcode_job.repetitions())
neardist = quasdist.nearest_probability_distribution()
correct_dist = {f'{key:0{quasdist._num_bits}b}': value for key, value in neardist.items()}
```

**Comment by richrines1** [comment] 2023-10-19 17:36
imo it was a mistake for us to just return quasi probabilities as if they were standard probabilities. i think this should be fixed in a server-side update to return both the actual and quasi probabilities in a separate fields

**Closed** 2023-10-20 14:57 UTC
Labels: enhancement, area/feature-request, cirq-superstaq, feature-request
