### ISSUE TITLE
Make multicore optional for pytest

### ISSUE THREAD

**Issue by pgoiporia** [Infleqtion/client-superstaq#990] opened 2024-07-12 15:30 UTC
I've noticed that running individual checks takes much longer with multicore pytest. This is because it takes time to instantiate and collect the workers. It would be useful to have pytest default to multicore but have the option to pass a flag that indicates I want to run on a single core.

**Comment by pgoiporia** [comment] 2024-07-16 16:00
Added suggestion. Maybe we default to multicore when using `./checks/pytest_.py` but default to running on a single core when we specify any files/specific tests.

**Comment by vtomole** [comment] 2024-07-25 16:16
Duplicate of https://github.com/Infleqtion/client-superstaq/issues/9

**Closed by vtomole** 2024-07-25 16:16 UTC
Labels: area/checks
